package fulltext.bo;
// Generated Aug 21, 2014 3:46:05 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChiTietSach generated by hbm2java
 */
@Entity
@Table(name="chi_tiet_sach"
    ,catalog="my_book"
)
public class ChiTietSach  implements java.io.Serializable {


     private ChiTietSachId id;
     private Sach sach;
     private TacGia tacGia;
     private ChungLoai chungLoai;
     private NhaXuatBan nhaXuatBan;

    public ChiTietSach() {
    }

    public ChiTietSach(ChiTietSachId id, Sach sach, TacGia tacGia, ChungLoai chungLoai, NhaXuatBan nhaXuatBan) {
       this.id = id;
       this.sach = sach;
       this.tacGia = tacGia;
       this.chungLoai = chungLoai;
       this.nhaXuatBan = nhaXuatBan;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="maSach", column=@Column(name="ma_sach", nullable=false, length=10) ), 
        @AttributeOverride(name="maTacGia", column=@Column(name="ma_tac_gia", nullable=false) ), 
        @AttributeOverride(name="maNxb", column=@Column(name="ma_nxb", nullable=false) ), 
        @AttributeOverride(name="maLoai", column=@Column(name="ma_loai", nullable=false) ) } )
    public ChiTietSachId getId() {
        return this.id;
    }
    
    public void setId(ChiTietSachId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ma_sach", nullable=false, insertable=false, updatable=false)
    public Sach getSach() {
        return this.sach;
    }
    
    public void setSach(Sach sach) {
        this.sach = sach;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ma_tac_gia", nullable=false, insertable=false, updatable=false)
    public TacGia getTacGia() {
        return this.tacGia;
    }
    
    public void setTacGia(TacGia tacGia) {
        this.tacGia = tacGia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ma_loai", nullable=false, insertable=false, updatable=false)
    public ChungLoai getChungLoai() {
        return this.chungLoai;
    }
    
    public void setChungLoai(ChungLoai chungLoai) {
        this.chungLoai = chungLoai;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ma_nxb", nullable=false, insertable=false, updatable=false)
    public NhaXuatBan getNhaXuatBan() {
        return this.nhaXuatBan;
    }
    
    public void setNhaXuatBan(NhaXuatBan nhaXuatBan) {
        this.nhaXuatBan = nhaXuatBan;
    }




}


