package fulltext.bo;
// Generated Aug 21, 2014 3:46:05 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChungLoai generated by hbm2java
 */
@Entity
@Table(name="chung_loai"
    ,catalog="my_book"
)
public class ChungLoai  implements java.io.Serializable {


     private Integer maLoai;
     private String tenLoai;
     private Set<ChiTietSach> chiTietSaches = new HashSet<ChiTietSach>(0);

    public ChungLoai() {
    }

    public ChungLoai(String tenLoai, Set<ChiTietSach> chiTietSaches) {
       this.tenLoai = tenLoai;
       this.chiTietSaches = chiTietSaches;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ma_loai", unique=true, nullable=false)
    public Integer getMaLoai() {
        return this.maLoai;
    }
    
    public void setMaLoai(Integer maLoai) {
        this.maLoai = maLoai;
    }

    
    @Column(name="ten_loai", length=100)
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chungLoai")
    public Set<ChiTietSach> getChiTietSaches() {
        return this.chiTietSaches;
    }
    
    public void setChiTietSaches(Set<ChiTietSach> chiTietSaches) {
        this.chiTietSaches = chiTietSaches;
    }




}


