package fulltext.bo;
// Generated Aug 21, 2014 3:46:05 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NhaXuatBan generated by hbm2java
 */
@Entity
@Table(name="nha_xuat_ban"
    ,catalog="my_book"
)
public class NhaXuatBan  implements java.io.Serializable {


     private Integer maNxb;
     private String tenNxb;
     private String diaChi;
     private String soDienThoai;
     private Set<ChiTietSach> chiTietSaches = new HashSet<ChiTietSach>(0);

    public NhaXuatBan() {
    }

	
    public NhaXuatBan(String tenNxb) {
        this.tenNxb = tenNxb;
    }
    public NhaXuatBan(String tenNxb, String diaChi, String soDienThoai, Set<ChiTietSach> chiTietSaches) {
       this.tenNxb = tenNxb;
       this.diaChi = diaChi;
       this.soDienThoai = soDienThoai;
       this.chiTietSaches = chiTietSaches;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ma_nxb", unique=true, nullable=false)
    public Integer getMaNxb() {
        return this.maNxb;
    }
    
    public void setMaNxb(Integer maNxb) {
        this.maNxb = maNxb;
    }

    
    @Column(name="ten_nxb", nullable=false, length=100)
    public String getTenNxb() {
        return this.tenNxb;
    }
    
    public void setTenNxb(String tenNxb) {
        this.tenNxb = tenNxb;
    }

    
    @Column(name="dia_chi", length=200)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="so_dien_thoai", length=20)
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhaXuatBan")
    public Set<ChiTietSach> getChiTietSaches() {
        return this.chiTietSaches;
    }
    
    public void setChiTietSaches(Set<ChiTietSach> chiTietSaches) {
        this.chiTietSaches = chiTietSaches;
    }




}


