package fulltext.bo;
// Generated Aug 21, 2014 3:46:05 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name="sach"
    ,catalog="my_book"
)
public class Sach  implements java.io.Serializable {


     private String maSach;
     private String tenSach;
     private Integer soTrang;
     private Date ngayXuatBan;
     private String moTa;
     private Set<ChiTietSach> chiTietSaches = new HashSet<ChiTietSach>(0);

    public Sach() {
    }

	
    public Sach(String maSach, String tenSach) {
        this.maSach = maSach;
        this.tenSach = tenSach;
    }
    public Sach(String maSach, String tenSach, Integer soTrang, Date ngayXuatBan, String moTa, Set<ChiTietSach> chiTietSaches) {
       this.maSach = maSach;
       this.tenSach = tenSach;
       this.soTrang = soTrang;
       this.ngayXuatBan = ngayXuatBan;
       this.moTa = moTa;
       this.chiTietSaches = chiTietSaches;
    }
   
     @Id 

    
    @Column(name="ma_sach", unique=true, nullable=false, length=10)
    public String getMaSach() {
        return this.maSach;
    }
    
    public void setMaSach(String maSach) {
        this.maSach = maSach;
    }

    
    @Column(name="ten_sach", nullable=false, length=200)
    public String getTenSach() {
        return this.tenSach;
    }
    
    public void setTenSach(String tenSach) {
        this.tenSach = tenSach;
    }

    
    @Column(name="so_trang")
    public Integer getSoTrang() {
        return this.soTrang;
    }
    
    public void setSoTrang(Integer soTrang) {
        this.soTrang = soTrang;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngay_xuat_ban", length=10)
    public Date getNgayXuatBan() {
        return this.ngayXuatBan;
    }
    
    public void setNgayXuatBan(Date ngayXuatBan) {
        this.ngayXuatBan = ngayXuatBan;
    }

    
    @Column(name="mo_ta", length=65535)
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sach")
    public Set<ChiTietSach> getChiTietSaches() {
        return this.chiTietSaches;
    }
    
    public void setChiTietSaches(Set<ChiTietSach> chiTietSaches) {
        this.chiTietSaches = chiTietSaches;
    }




}


