package fulltext.bo;
// Generated Aug 21, 2014 3:46:05 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TacGia generated by hbm2java
 */
@Entity
@Table(name="tac_gia"
    ,catalog="my_book"
)
public class TacGia  implements java.io.Serializable {


     private Integer maTacGia;
     private String tenTacGia;
     private String diaChi;
     private String soDienThoai;
     private Set<ChiTietSach> chiTietSaches = new HashSet<ChiTietSach>(0);

    public TacGia() {
    }

	
    public TacGia(String tenTacGia) {
        this.tenTacGia = tenTacGia;
    }
    public TacGia(String tenTacGia, String diaChi, String soDienThoai, Set<ChiTietSach> chiTietSaches) {
       this.tenTacGia = tenTacGia;
       this.diaChi = diaChi;
       this.soDienThoai = soDienThoai;
       this.chiTietSaches = chiTietSaches;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ma_tac_gia", unique=true, nullable=false)
    public Integer getMaTacGia() {
        return this.maTacGia;
    }
    
    public void setMaTacGia(Integer maTacGia) {
        this.maTacGia = maTacGia;
    }

    
    @Column(name="ten_tac_gia", nullable=false, length=100)
    public String getTenTacGia() {
        return this.tenTacGia;
    }
    
    public void setTenTacGia(String tenTacGia) {
        this.tenTacGia = tenTacGia;
    }

    
    @Column(name="dia_chi", length=200)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="so_dien_thoai", length=20)
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tacGia")
    public Set<ChiTietSach> getChiTietSaches() {
        return this.chiTietSaches;
    }
    
    public void setChiTietSaches(Set<ChiTietSach> chiTietSaches) {
        this.chiTietSaches = chiTietSaches;
    }




}


